name: Java CI with Gradle

# main브랜치에 push 혹은 pull_request 요청이 올 경우 CI 시작
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # spring build 시작
  spring-build:

    # ubuntu 최신 환경에서 빌
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # gradle 권한 644 -> 755
    - name: Build with Gradle Wrapper
      run: ./gradlew build